### ISSUE TITLE
Running the script: UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by jonwhittlestone** [jamiehaywood/hl#9]
Sorry, JS simple question here.

What am I doing wrong running this?

I'm on `node` v12.13.1 and `tsc` 4.1.2

```
➜  use-hargreaves-lansdown node index.js
(node:26904) UnhandledPromiseRejectionWarning: TypeError: hargreaves_lansdown_1.default is not a constructor
    at /home/jon/code/playground/use-hargreaves-lansdown/index.js:51:22
    at step (/home/jon/code/playground/use-hargreaves-lansdown/index.js:33:23)
    at Object.next (/home/jon/code/playground/use-hargreaves-lansdown/index.js:14:53)
    at /home/jon/code/playground/use-hargreaves-lansdown/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/jon/code/playground/use-hargreaves-lansdown/index.js:4:12)
    at /home/jon/code/playground/use-hargreaves-lansdown/index.js:40:23
    at Object.<anonymous> (/home/jon/code/playground/use-hargreaves-lansdown/index.js:68:7)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
(node:26904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26904) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jamiehaywood** [comment]
hi jon, thanks for getting in touch.

It's not entirely clear to me how you're trying to consume the `hargreaves-lansdown` package, but there are a couple of things:
1. Your `package.json` looks malformed.
2. You've got a TypeScript `index.ts` file, but no `tsconfig.json`

To simplify things in your case:
1. delete your `package.json` file and then run `yarn init` in the root folder. Follow the CLI steps
2. add `"type": "module",` to your `package.json` file, above `"dependencies":{`
3. run `yarn add hargreaves-lansdown`
4. instead of using a TypeScript file, just use vanilla JS - it's easier for quick start. change your `.ts` file extension to `.js`
5. run `node index.js` 
6. 💵

**Comment by jonwhittlestone** [comment]
Thanks for the quick reply Jamie :+1: 

I now get this

```
➜  use-hargreaves-lansdown node index.js
/home/jon/code/playground/use-hargreaves-lansdown/index.js:1
import HL from 'hargreaves-lansdown'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
➜  use-hargreaves-lansdown  
```

![image](https://user-images.githubusercontent.com/1681212/114977897-5db3d080-9e80-11eb-82d7-6cf1fc6386b3.png)

**Comment by jamiehaywood** [comment]
hi @jonwhittlestone - my apologies I should have been more clear.

1. you need to add `"type": "module",` on any line above license

2. you need to run `yarn add hargreaves-lansdown` in the terminal

**Comment by moritonal** [comment]
Hi @jonwhittlestone,

I'd advise changing your password and secure number.

Do not rely on a weak blur filter to annonymise data. Five seconds in photoshop tells me your password is roughly `Matartng18-Residency-law98`, DOB starts with a few 1's (I know it all but given you can't change it I won't post), and the secure number is probably `9*5788`.

Hargreaves almost definetely have a clause in their T&C explaining that if you post your details publically then it's not their fault when you are hacked. I put very little effort in, so someone else could likely get much better results than me.

**Comment by jonwhittlestone** [comment]
Thanks @jamiehaywood - those steps, plus upgrading my version of node, did the trick

Thankyou @moritonal ! That really is saving my bacon.

Screenshots redacted and credentials changed.
